### ISSUE TITLE
Plugin does not work with node 7.0+

### ISSUE THREAD

**Issue by eiennohito** [typesafehub/npm#9]
```
[info] Wrote /Users/eiennohito/dev/scala/aozora-getter/gui/target/scala-2.11/analyzer-gui_2.11-1.0-SNAPSHOT.pom
[info]
[error] module.js:474
[error]     throw err;
[error]     ^
[error]
[error] Error: Cannot find module 'internal/fs'
[error]     at Function.Module._resolveFilename (module.js:472:15)
[error]     at Function.Module._load (module.js:420:25)
[error]     at Module.require (module.js:500:17)
[error]     at require (internal/module.js:20:19)
[error]     at evalmachine.<anonymous>:17:20
[error]     at Object.<anonymous> (/Users/eiennohito/dev/scala/aozora-getter/project/target/node-modules/webjars/npm/node_modules/graceful-fs/fs.js:11:1)
[error]     at Module._compile (module.js:573:32)
[error]     at Object.Module._extensions..js (module.js:582:10)
[error]     at Module.load (module.js:490:32)
[error]     at tryModuleLoad (module.js:449:12)
```

On 6.8.0 there is a following line in output:

```
(node:71326) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
```

Probably, upgrading npm dependency will work, 2.12.2 seems a bit ancient for today.

**Comment by benmccann** [comment]
I've upgraded to npm 2.14.14 though that's not a huge jump

From James on the Play mailing list:
>It's using Trireme, a JVM implementation of node.js.  Trireme only implements node 0.10.32, and is not likely to provide support for node 4 in the near future, see https://github.com/apigee/trireme#what-version-of-nodejs-does-trireme-support.
I suggest to fix we:
Implement something that detects whether it's running on Node or Trireme, and if running on Trireme, output a big fat warning saying running npm on Trireme is not supported, with instructions on how to install node and ensure that sbt-js-engine will detect and use that.

You might have to wait a bit for us to implement, but if you want to take a stab we would merge a PR.

**Comment by mkurz** [comment]
+1 Looking forward to Node >=7 support as well

**Comment by benmccann** [comment]
Note for detection logic: CommonNode and Node work. PhantomJs, Rhino, and Trireme don't work.

**Comment by benmccann** [comment]
I sent a PR to enable this: https://github.com/typesafehub/js-engine/pull/54

**Comment by benmccann** [comment]
PR here: https://github.com/typesafehub/npm/pull/16

**Comment by mkurz** [comment]
This has been fixed by #16 and can be closed.
